%%! spec: 03/09/2021

sequenceDiagram
    autonumber
    participant F as frontend
    participant B as Norren
    participant Db as database
    # participant cache as cache
    participant TP as Token Provider # shared service
    participant C as CNode

    F ->>+ C : Save current code
    C -->>- F : ✅ 200 OK

    F ->>+ B : POST /submissions

    B ->>+ Db : Create new submission
    Db -->>- B : submission 123 created

    B ->>+ Db : Fetch non-sample test cases
    Db -->>- B : test cases of 123

    rect rgb(255, 0, 0, 0.1)
    B ->>+ TP : authorize submission

    TP ->>+ Db: Fetch shared secret
    Db ->>- TP: JWT secret    

    TP -->>- B : new short-lived JWT token
    Note right of B: {iss:norren,aud:cnode,sub:submission}
    end

    B ->>+ C : Evaluate submission (data) with given test cases
    Note right of B: with Authorization: Bearer <JWT token>

    C ->>+ TP : verify bearer token
    TP -->>- C : token valid

    C -->>- B : ✅ 200 OK (evaluation results)

    B ->> B : Save submission result

    B -->>- F : ✅ 200 OK
    Note right of F: body with status:accepted
