%%! spec: 20/12/2021
%% WIP

sequenceDiagram
    autonumber

    participant C as Client
    participant API as API # controller
    participant VL as Validation # using Joi
    participant M as O2O Mapper # using @automapper/nestjs
    participant App as Domain # service
    participant Db as Database # repository

    C ->>+ API : POST /users/self/forgot_password
    activate API
    Note right of C : body: UserForgotPasswordDto shape

    API ->>+ VL : parse (validate & transform) the JSON
    VL -->>- API : payload data parsed
    Note right of API : UserForgotPasswordDto

    API ->>+ App : recover password of user with supplied e-mail

    App ->> App : generate a new authorization opaque token
    activate App
    deactivate App

    App ->>+ Db : store the new token
    Db -->>- App : saved 'token' as a 'authKey'

    App ->> App : send e-mail with password recovery link with the token
    activate App
    deactivate App

    App -->>- API : PasswordResetRoDto

    API -->>+ C : 201 OK
    Note right of C : body: PasswordResetRoDto

    deactivate API

    %% Later on ...

    C ->>+ API : PATCH /users/{token}/reset_password
    %% activate API
    Note right of C : body: UserResetPasswordDto shape

    API ->>+ VL : parse (validate & transform) the JSON
    VL -->>- API : payload data parsed
    Note right of API : UserResetPasswordDto

    API ->>+ App : change password of user with supplied token

    App ->>+ Db : find user with 'token' as a 'authKey'
    Db -->>- App : UserEntity

    App ->> App : check if token is expired
    activate App
    deactivate App
    Note right of App: Token is valid

    App ->>+ Db : Save the new password & invalidate the 'authKey'
    Db -->>- App : UserEntity

    App -->>- API : UserEntity

    API -->>+ C : 201 OK
    Note right of C : body: DoneRoDto

    deactivate API
